// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQECfhGUgce_Msr-y-1WSmjhQxMM0t75g',
    appId: '1:789576819252:android:5e6b7ab3e6540b6face061',
    messagingSenderId: '789576819252',
    projectId: 'yeni-kayan-ekran',
    storageBucket: 'yeni-kayan-ekran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe5E67Hf3ykp2tlgS9li9xneRWLO-IwjY',
    appId: '1:789576819252:ios:ad66396284548c89ace061',
    messagingSenderId: '789576819252',
    projectId: 'yeni-kayan-ekran',
    storageBucket: 'yeni-kayan-ekran.appspot.com',
    iosClientId: '789576819252-mv7i3r6l8d23m23uo31hua96s8kr68nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeniKayanEkran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe5E67Hf3ykp2tlgS9li9xneRWLO-IwjY',
    appId: '1:789576819252:ios:ad66396284548c89ace061',
    messagingSenderId: '789576819252',
    projectId: 'yeni-kayan-ekran',
    storageBucket: 'yeni-kayan-ekran.appspot.com',
    iosClientId: '789576819252-mv7i3r6l8d23m23uo31hua96s8kr68nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeniKayanEkran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtfHV9s2RXRQPzuXDbzrc31uXgsLb7ZWk',
    appId: '1:789576819252:web:10b25e01e75baa56ace061',
    messagingSenderId: '789576819252',
    projectId: 'yeni-kayan-ekran',
    authDomain: 'yeni-kayan-ekran.firebaseapp.com',
    storageBucket: 'yeni-kayan-ekran.appspot.com',
  );
}
